services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf.d:/etc/nginx/conf.d
    tty: true
    restart: always
    networks:
      fim_network:
        ipv4_address: 10.0.100.5

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 4173:4173
    volumes:
      - ./web:/app/src
    tty: true
    restart: always
    networks:
      fim_network:
        ipv4_address: 10.0.100.10

  federation_orchestrator:
    build:
      context: ./federation-orchestrator
      dockerfile: Dockerfile
    volumes:
      - ./federation-orchestrator:/app/src
    ports:
      - 9000:9000
    tty: true
    restart: always
    networks:
      fim_network:
        ipv4_address: 10.0.100.20

  feed_collector:
    build:
      context: ./feed-collector
      dockerfile: Dockerfile
    volumes:
      - ./feed-collector:/app/src
    ports:
      - 8000:8000
    tty: true
    restart: always
    networks:
      fim_network:
        ipv4_address: 10.0.100.30

  insights_api:
    build:
      context: ./insights-api
      dockerfile: Dockerfile
    volumes:
      - ./insights-api:/app/src
    ports:
      - 9500:9500
    tty: true
    restart: always
    networks:
      fim_network:
        ipv4_address: 10.0.100.40

networks:
  fim_network:
    ipam:
      driver: default
      config:
        - subnet: 10.0.100.0/24
