name: FIM Web E2E Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: |
          pwd
          cd /home/runner/work/FIM/FIM/web/fim-web
          npm install -g pnpm
          pnpm install --frozen-lockfile

      - name: Run FIM-Web in dev mode
        run: |
          cd /home/runner/work/FIM/FIM/web/fim-web
          pnpm dev &

      - name: Install Playwright Browsers
        run: |
          cd /home/runner/work/FIM/FIM/e2e
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          cd /home/runner/work/FIM/FIM/e2e
          pnpm install
          npx playwright test


      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
