name: FIM Web E2E Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        working-directory: web/fim-web
        run: npm ci

      - name: Run FIM-Web in dev mode
        working-directory: web/fim-web
        run: npm run dev

      - name: Install Playwright Browsers
        working-directory: e2e
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: e2e
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
